- name: Deploy Three Tier App
  hosts: localhost
  connection: local
  gather_facts: false
  tags:
  - smoketest

  tasks:

  - name: Retrieve Instances from OpenStack
    os_server_info:
      cloud: openstack
      region_name: regionOne
    register: os_instances

  - name: Add hosts from instances
    add_host:
      name: '{{ item.public_v4 }}'
      ansible_user: cloud-user
      ansible_ssh_private_key_file: "~/.ssh/openstack.pem"
      group:
        - "{{ item.metadata.group }}"
        - "{{ item.metadata.deployment_name }}"
    loop: '{{ os_instances.openstack_servers }}'

- name: Gather database facts
  hosts: database_servers
  gather_facts: true

  tasks: []

- name: Setup Repos
  hosts: app_servers:load_balancers:database_servers
  gather_facts: false
  become: true
  
  tasks:

    - name: Copy repo file
      copy:
        src: ../files/open_three-tier-app.repo
        dest: /etc/yum.repos.d/open_three-tier-app.repo

- import_playbook: provision_database_tier.yml
- import_playbook: provision_app_tier.yml
- import_playbook: provision_load_balancer_tier.yml
- import_playbook: smoke_tests.yml
